language: php

php:
    - 5.4
    - 5.5

before_script:
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash
    - phpcs --config-set default_standard PEAR
    - composer install

script:
    - phpcs --standard=build/travis-ci-phpcs.xml --extensions=php --ignore=vendor .
    - phpunit -c tests/phpunit.xml
